### ISSUE TITLE
Bounded context dropping a reference

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/bounded-context#2]
In some cases, the `isReference` field can be true in the `SystemContext` object, but becomes false in after being turned into a `BoundedContext`. Issue discovered when processing the [TMS2](https://github.com/cloudhubs/tms2) repo (TMS2 is used because it omits the QMS microservice, which had JPA annotations on the methods instead of fields which caused processing it to fail).

Steps to reproduce:
1. Pull latest prophet-utils changes
2. Pull the [TMS2](https://github.com/cloudhubs/tms2) repo
3. Set the appropriate root path and ms paths to the TMS2 project in src > test > resources > application.properties
4. Run the `generateTms2Template` test in `ProphetUtilsTest.java`
5. Examine the resulting `bounded-context.html` file.

The expected result is:
![expected](https://user-images.githubusercontent.com/57876607/74671925-c8c92080-5171-11ea-8bab-f94b9119f15e.jpg)

The actual result is:
![actual](https://user-images.githubusercontent.com/57876607/74671944-d383b580-5171-11ea-8b3f-32a5bb37c075.jpg)

Examining the system context shows two fields with `isReference==true` in the `Question` entity:
![systemContext](https://user-images.githubusercontent.com/57876607/74671989-e4342b80-5171-11ea-9993-996beca0dd7d.jpg)

Examining bounded context shows only one field:
![boundedContext](https://user-images.githubusercontent.com/57876607/74672016-f746fb80-5171-11ea-8fa2-05a9e87b432d.jpg)

**Comment by vinbush** [comment]
@i-laird Also the type of the description field above got changed from String to Choice, but I'm guessing that's not related to this issue.

**Comment by i-laird** [comment]
Just saw this, and I will work to fix it tomorrow.

**Comment by i-laird** [comment]
Thanks for the UML diagrams, those will make debugging much faster

**Comment by i-laird** [comment]
@vinbush issue should be resolved. Note that I updated JParser to version 7 so it will need to be rebuilt
