### ISSUE TITLE
Merging two entities

### ISSUE THREAD

**Issue by svacina** [cloudhubs/bounded-context#4]
When two entites are merged, same fields are merged, but fields that are not same are dropped. But they should not be dropped, but included into the new entity.

**Comment by diptadas** [comment]
- https://github.com/cloudhubs/bounded-context/commit/db132513870a0efce6f7081919c3abeb31fdd2dd
- https://github.com/cloudhubs/prophet-utils/commit/8c61fe8312ef67c07c30ece67588860b25f563a6
