### ISSUE TITLE
Check both side of relationship

### ISSUE THREAD

**Issue by svacina** [cloudhubs/bounded-context#5]
In case:

```
class Choice{
@JsonIgnore
    @NotNull
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(updatable = false)
    private Question question;
}

class Question {
@OneToMany(mappedBy = "question", fetch = FetchType.EAGER)
    private List<Choice> choices;

}
```

![image](https://user-images.githubusercontent.com/20039965/82261242-4db80780-9924-11ea-8a2f-88bed51857b9.png)

But the relations should one to many.

**Comment by diptadas** [comment]
Related commit https://github.com/cloudhubs/bounded-context/commit/8c7c6329e74a4cb1310cc69dce50ad3073a6c8fe
